apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Release.Name }}-analysis
spec:
  metrics:
    - name: error-rate
      interval: 30s
      count: 5
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{status=~"5.."}[2m])) or vector(0)
            /
            (sum(rate(http_requests_total[2m])) or vector(1)) * 100
      successCondition: result[0] < 1

    - name: p95-response-time
      interval: 30s
      count: 5
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          query: |
            histogram_quantile(0.95,
              sum(rate(http_request_duration_seconds_bucket[2m])) by (le)
            ) or vector(0)
      successCondition: result[0] < 0.5
